<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-28T19:52:41 IST" name="Default suite" finished-at="2022-08-28T19:53:06 IST" duration-ms="25547">
    <groups>
    </groups>
    <test started-at="2022-08-28T19:52:41 IST" name="Default test" finished-at="2022-08-28T19:53:06 IST" duration-ms="25547">
      <class name="TestCases.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:41 IST" name="setup" finished-at="2022-08-28T19:52:53 IST" duration-ms="12289" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifykitelogoTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:53 IST" name="verifykitelogoTest" finished-at="2022-08-28T19:52:53 IST" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifykitelogoTest -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:53 IST" name="end" finished-at="2022-08-28T19:52:54 IST" duration-ms="474" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifykitelogoTest status=SUCCESS method=LoginPageTest.verifykitelogoTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:54 IST" name="setup" finished-at="2022-08-28T19:52:59 IST" duration-ms="4736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyloginTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:59 IST" name="verifyloginTest" finished-at="2022-08-28T19:52:59 IST" duration-ms="636" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Keys to send should be a not null CharSequence]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at com.sun.proxy.$Proxy16.sendKeys(Unknown Source)
at Pages.LoginPage.verifylogin(LoginPage.java:42)
at TestCases.LoginPageTest.verifyloginTest(LoginPageTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyloginTest -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:52:59 IST" name="end" finished-at="2022-08-28T19:53:00 IST" duration-ms="741" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyloginTest status=FAILURE method=LoginPageTest.verifyloginTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:53:00 IST" name="setup" finished-at="2022-08-28T19:53:04 IST" duration-ms="4205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifytittleTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:53:04 IST" name="verifytittleTest" finished-at="2022-08-28T19:53:06 IST" duration-ms="1582" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Base.TestBase.readexcelsheetfile(TestBase.java:43)
at TestCases.LoginPageTest.verifytittleTest(LoginPageTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytittleTest -->
        <test-method is-config="true" signature="end(org.testng.ITestResult)[pri:0, instance:TestCases.LoginPageTest@65f095f8]" started-at="2022-08-28T19:53:06 IST" name="end" finished-at="2022-08-28T19:53:06 IST" duration-ms="585" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifytittleTest status=FAILURE method=LoginPageTest.verifytittleTest()[pri:0, instance:TestCases.LoginPageTest@65f095f8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- TestCases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
